### ISSUE TITLE
Создать swap implementation standards checkbox list

### ISSUE THREAD

**Issue by vladiuz1** [swaponline/sips#2]
## Идея

Прошу обсудить идею (назовем данный тикет не issue а неким **Implementation Flow Improvement Proposal**)

Создать список чекбоксов, где каждый чекбокс описывает конкретный принцип, требование или тест имплементации протокола, которые должны быть выполнены или соблюдены перед тем как имплементация свопа конкретной пары пошла в мейннет.

Каждый чекбокс при этом отмечается по мере имплементации свопа между конкретной парой.

Каждый чекбокс должен содержать назавание принципа/требования/теста и ссылку на более подробное описание, мотивацию и обоснование, возможно с примерами имплементации.

Для каждой версии протокола обмена у нас будет своя версия такого списка. При этом каждый чекбокс может тоже иметь свою версию.

### Примеры принципов/стандартов/требований/тестов

This is a checkbox list for implementation of atomic swap of dogs for cats **version 1.0**

 - [ ] Make sure you don't exchange less than 2 cats for dogs. [Minimum cats **requirement** v0.1](url)
 - [ ] Make sure the dogs are clean. [Cleaning dogs **standard** v0.3](url)
 - [ ] Make sure cats are passed over first. [Cats always go first **principle** v0.43](url)
 - [ ] Make sure the cats are not pregnant. [Pregnancy **test** procedures v.1.23](url)

Из более реальных примеров чекбокосов:

* проверка длины секрета
* маркет тейкер - всегда хранитель секрета

### Шаблоны

При этом при создании тикета на имплементацию свопа конкретной пары, всегда будет висеть шаблон, в котором уже будет иметься checkbox list самой актуальной на данный момент версии

### Milestones

Чекбоксы могут быть разделены на milestones. То есть у каждой имплементации может быть разная глубина. Например - только Basic Swap имплементация - бесплатный медленный своп (то как это происходит сейчас), Faster Swap имплементация - ускоренный своп, когда маркет тейкер подписывает сразу 2 транзакции (send + claim), Destination Address - фича с кастомным адресом назначения, Prepaid Claim фича - платный когда мы сами оплачиваем "claim" своим эфиром итд итп...

### 2 типа checkbox list

1. для свопов
2. для кошелька

### Страница статуса

Если мы делаем вышеописанное, неплохо было бы сделать страничку публичную, которая имеет список всех криптовалют, а так-же всех пар и на каждую из пар было бы круто видеть в реальном времени статусы имплементации, сгенерированные прямо из гитхабовских issues с боксами.

Что то типа swapready.net только наш собственный

**Comment by noxonsu** [comment]
https://github.com/swaponline/MultiCurrencyWallet/blob/master/docs/ADD_BLOCKCHAIN.md
